version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27010:27017"  # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Replace with your MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: password  # Replace with your MongoDB root password
    volumes:
      - mongodb_data:/data/db  # Persist data

volumes:
  mongodb_data:
    driver: local
